"""
This module implements the confidence checker component of the FORAGER pipeline.
The confidence checker estimates the reliability of responses generated by the LLM
by evaluating their alignment with retrieved context documents. It provides a
numerical confidence score indicating the likelihood that the answer is supported
by the provided evidence.

Primary Functions:
- compute_confidence: Calculates a confidence score based on the semantic similarity
  between the LLM's response and the retrieved documents.
- Additional helper functions for text preproecessing and similarity computations.

Usage:
This module is intended to be used after generating an answer and retrieving supporting
documents. The confidence score can be used to determine whether the answer should be
accepted, discarded, or refined in subsequent iterations of the Prompt Lock Loop (PLL).
"""
__docformat__ = "google"
from embedder import search_database
from bs import detect_bs
from runner import get_llm_response

prompt = "Insert original or reworked prompt here"

#Get llm response
llm_response = get_llm_response(prompt)

#Set number of nearest-neighbor chunks to use to compute similarity score
k = 5

# Compare llm response to chunks in database
results, scores = search_database(llm_response, k)

# Compute the average of the scores of the top 5 most similar documents to get a sense
# of how similar the llm's answer is to the database.
similarity_score = sum(scores[0]) / len(scores[0])
print(similarity_score)

# Get the evaluation label of the llm's response
eval_label = detect_bs(llm_response, results)

def confidence_checker(eval_label, similarity_score):
    """
    Determines a final confidence score or decision based on the evaluation label 
    (e.g., NLI classification) and the similarity score between the LLM response 
    and the supporting documents.

    Args:
        eval_label (str): The classification label assigned to the answer, typically 
                          values like 'Supported', 'Unsupported', or 'Contradicted'.
        similarity_score (float): A numerical value representing the semantic similarity 
                                  between the LLM response and the supporting documents,
                                  typically ranging from 0 to 1.

    Returns:
        float: A final confidence score (or decision value) reflecting both logical 
               consistency (from eval_label) and semantic alignment (from similarity_score).
               This score can be used to determine whether to accept, discard, or 
               regenerate the LLM answer within the FORAGER Prompt Lock Loop (PLL).

    Notes:
        - 'Supported' responses will generally yield higher confidence.
        - 'Unsupported' or 'Contradicted' responses will lower the confidence score, 
          even if the similarity is high, helping to mitigate false positives.
    """
    if eval_label == "Supported" and similarity_score >= 0.7:
        confidence = "High Confidence"
    elif eval_label == "Supported" and similarity_score < 0.7:
        confidence = "Medium"
    elif eval_label == "Unsupported":
        confidence = "Low"
    elif eval_label == "Contradicted":
        confidence = "Zero Confidence"
    
    return confidence