"""
This module implements the confidence checker component of the FORAGER pipeline.
The confidence checker estimates the reliability of responses generated by the LLM
by evaluating their alignment with retrieved context documents. It provides a
numerical confidence score indicating the likelihood that the answer is supported
by the provided evidence.

Primary Functions:
- compute_confidence: Calculates a confidence score based on the semantic similarity
  between the LLM's response and the retrieved documents.
- Additional helper functions for text preproecessing and similarity computations.

Usage:
This module is intended to be used after generating an answer and retrieving supporting
documents. The confidence score can be used to determine whether the answer should be
accepted, discarded, or refined in subsequent iterations of the Prompt Lock Loop (PLL).
"""

import os
import sys
from FORAGER.embedder import FAISSEmbedder
from typing import List, Tuple
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
__docformat__ = "google"

def check_confidence(embedder: FAISSEmbedder, claim, eval_label, supporting_docs: List[str], k: int = 3):
    """
    Determines a final confidence label based on the evaluation label 
    (e.g., NLI classification) and the similarity score between the LLM response 
    and the supporting documents.

    Args:
        eval_label (str): The classification label assigned to the answer, typically 
                          values like 'Supported', 'Unsupported', or 'Contradicted'.

    Returns:
        confidence (str): A final confidence label reflecting both logical 
               consistency (from eval_label) and semantic alignment (from similarity_score).
               This label can be used to determine whether to accept, discard, or 
               regenerate the LLM answer within the FORAGER Prompt Lock Loop (PLL).

    Notes:
        - 'Supported' responses will generally yield higher confidence.
        - 'Unsupported' or 'Contradicted' responses will lower the confidence, 
          even if the similarity is high, helping to mitigate false positives.
    """
    if claim:
        # Compare llm claim to nearest k chunks in database 
        # Compute the average of the scores of the top 5 most similar documents to get a sense
        # of how similar the llm's answer is to the database.
        claim_embedding = embedder.embed_text(claim)
        doc_embeddings = [
            embedder.embed_text(doc["text"]) if isinstance(doc, dict) else embedder.embed_text(doc)
            for doc in supporting_docs
        ]

        scores = [
            embedder.cosine_similarity(claim_embedding, doc_embedding)
            for doc_embedding in doc_embeddings
        ]
        
        similarity_score = sum(scores) / len(scores) if scores else 0
        print(f"\033[1;96mSimilarity Score: {similarity_score}\033[0m")
    else:
        print("\033[1;91mLLM did not give an output!\033[0m")
        similarity_score = 0
    
    if eval_label == "Supported" and similarity_score >= 0.7:
        confidence = "High"
    elif eval_label == "Supported" and similarity_score < 0.7:
        confidence = "Medium"
    elif eval_label == "Unsupported":
        confidence = "Low"
    elif eval_label == "Contradicted" or similarity_score == 0:
        confidence = "Zero"
    else:
        print(f"[WARN] Unrecognized eval_label: {eval_label}. Defaulting to Low confidence.")
        confidence = "Low"
    
    return confidence