"""
This module implements the confidence checker component of the FORAGER pipeline.
The confidence checker estimates the reliability of responses generated by the LLM
by evaluating their alignment with retrieved context documents. It provides a
numerical confidence score indicating the likelihood that the answer is supported
by the provided evidence.

Primary Functions:
- compute_confidence: Calculates a confidence score based on the semantic similarity
  between the LLM's response and the retrieved documents.
- Additional helper functions for text preproecessing and similarity computations.

Usage:
This module is intended to be used after generating an answer and retrieving supporting
documents. The confidence score can be used to determine whether the answer should be
accepted, discarded, or refined in subsequent iterations of the Prompt Lock Loop (PLL).
"""

__docformat__ = "google"
from embedder import search_database
from bs import detect_bs

# Test Cases
llm_response_1 = "Random response here."
# eval label: Supported
# similarity score: 0.6053619
# Confidence label: Medium

llm_response_2 = "Heterogeneous integration is the process of combining chips, chiplets, and other chip components into packages."
# Supported
# 0.82095444
# High Confidence

llm_response_3 = "George Washington was the first president of the United States."
# Supported
# 0.46574384
# Medium

llm_response_4 = "Heterogeneous integration is the process of singing a lullaby to put a baby to sleep."
# Supported
# 0.7159858
# Medium Confidence
# Changed similarity threshold for high confidence from 0.7 to 0.75

llm_response_5 = "Heterogeneous integration involves chiplets."
# Error??

llm_response_6 = "Heterogeneous integration is important for the advancement of silicon chip design."
# Supported
# 0.8119961
# High Confidence

llm_response_7 = ""
# Contradicted
# 0
# Zero Confidence
# Caught this edge case

llm_response_8 = "tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt."
# Contradicted
# 0.62369937
# Zero Confidence

llm_response_9 = "Heterogeneous integration is an outdated technology that has no relevance today." 
# Supported
# 0.6657399
# Medium

llm_response_10 = "Heterogeneous integration refers to the use of advanced packaging technologies " \
                  "to combine smaller, discrete chiplets—physically realized and tested (hardened) pieces" \
                  " of IP designed to each perform a particular logical function—into one system in package (SiP)."
# Supported
# 0.8357425
# High Confidence

def get_label_and_score(llm_response):
    """
    Returns an evaluation label and a similarity score for a given LLM response.

    Arguments:
        llm_response (str): The LLM's response to the user's prompt or a refined prompt

    Returns:
        eval_label (str): Evaluation label from the BS detector, usually "Supported," 
                            "Unsupported," or "Contradicted"
        similarity_score (float): Decimal between 0 and 1 representing the average dot 
                                    product similarity between the LLM's response and the
                                    corpus.
    """

    if llm_response:
        # Set number of nearest-neighbor chunks to use to compute similarity score
        k = 5

        # Compare llm response to chunks in database
        results = search_database(llm_response, k)

        # Compute the average of the scores of the top 5 most similar documents to get a sense
        # of how similar the llm's answer is to the database.
        scores = []
        for dict_ in results:
            scores.append(dict_["score"])

        similarity_score = sum(scores) / len(scores)
        print(f"\033[1;96mSimilarity Score: {similarity_score}\033[0m")

        # Get the evaluation label of the llm's response
        eval_label = detect_bs(llm_response, results)

        return eval_label, similarity_score
    else:
        print("\033[1;91mLLM did not give an output!\033[0m")
        eval_label = "Contradicted"
        similarity_score = 0
        return eval_label, similarity_score

def confidence_checker(eval_label, similarity_score):
    """
    Determines a final confidence score or decision based on the evaluation label 
    (e.g., NLI classification) and the similarity score between the LLM response 
    and the supporting documents.

    Args:
        eval_label (str): The classification label assigned to the answer, typically 
                          values like 'Supported', 'Unsupported', or 'Contradicted'.
        similarity_score (float): A numerical value representing the semantic similarity 
                                  between the LLM response and the supporting documents,
                                  typically ranging from 0 to 1.

    Returns:
        float: A final confidence score (or decision value) reflecting both logical 
               consistency (from eval_label) and semantic alignment (from similarity_score).
               This score can be used to determine whether to accept, discard, or 
               regenerate the LLM answer within the FORAGER Prompt Lock Loop (PLL).

    Notes:
        - 'Supported' responses will generally yield higher confidence.
        - 'Unsupported' or 'Contradicted' responses will lower the confidence score, 
          even if the similarity is high, helping to mitigate false positives.
    """
    if eval_label == "Supported" and similarity_score >= 0.75:
        confidence = "High Confidence"
    elif eval_label == "Supported" and similarity_score < 0.75:
        confidence = "Medium Confidence"
    elif eval_label == "Unsupported":
        confidence = "Low Confidence"
    elif eval_label == "Contradicted":
        confidence = "Zero Confidence"
    
    return confidence

if __name__ == "__main__":
    eval_label, similarity = get_label_and_score(llm_response_4)
    confidence_label = confidence_checker(eval_label, similarity)
    print(eval_label)
    print(similarity)
    print(confidence_label)