"""
What this file does:
Using the jsonl file with each line being a separate json representing a chunk...
1. Embeds each chunk
2. Stores each embedded chunk in FAISS database
3. Includes search function

Potential next steps:
Modify so embedder can take chunks from another file besides just chunks.jsonl, if necessary
"""

import os 
from sentence_transformers import SentenceTransformer
import numpy as np
import faiss
import json

# Initialize global variables
dim = 768 # Length of vectors generated by this embedding model
faiss_db = faiss.IndexFlatIP(dim)
chunks = []
embeddings = []
prefix = "Represent this sentence for retrieval: "

# Start by preparing the embedding model
model = SentenceTransformer("BAAI/bge-base-en-v1.5")

# Important filepaths listed here
chunk_filepath = "FORAGER_corpus/heterogenous_integration/chunks/chunks.jsonl"

test_chunk_filepath = "FORAGER_corpus/heterogenous_integration/chunks/test_chunks.jsonl"

faiss_db_filepath = "FORAGER/vector_database/index_db.faiss"
os.makedirs(os.path.dirname(faiss_db_filepath), exist_ok=True)

def embed_chunks(data, m, n):
    """
    Takes one chunk at a time from the new additions to chunks.jsonl file (or other inputted file) and embeds it using BGE model

    Arguments: 
        filepath: The file path of the JSONL document containing the chunks genereated by ingestor.py and chunker.py
        m: Starting chunk entry
        n: Ending chunk entry
    Returns:
        embeddings: A 2-D numpy array of vectors, each representing a chunk

    Variable type info: 
        chunk - dictionary (and each line in the JSONL file is a chunk)
        list of chunks - Python list
        text in chunk - one value in the chunk dictionary associated with "text" key
        "embeddings" - 2-D array (specifically "np.ndarray") with all the vectors. Each vector has a length of 768 using the BGE model
        Each element of "embeddings" is also of the type np.ndarray
        The dimensions of the "embeddings" array are [(length of chunk file), 768]
    """

    global prefix
    global embeddings

    # Select chunks to embed
    chunks_to_embed = data[m:n]
    print(f"\033[1;94mEmbedding {len(chunks_to_embed)} chunks...\033[0m\n")

    # Extract and prefix the text
    texts = [prefix + d["text"] for d in chunks_to_embed] #The BGE model expects the prefix to come before what we want to embed
    len_before_embed = len(embeddings)

    # Embed each chunk and normalize the resulting vector. Convert to float32 for insertion into FAISS index
    embeddings = model.encode(texts, normalize_embeddings = True).astype("float32")
    print(f"\033[1;92m✅ {len(embeddings) - len_before_embed} chunks successfully embedded!\033[0m\n")

    # Return the 2-D array of vectors
    return embeddings

def initial_embed_and_build(filepath):
    """
    Run this once when first running FORAGER to embed the first set of chunks and create the FAISS database

    Arguments:
        filepath: path to the JSONL file containing the chunks to be embedded

    Returns:
        embeddings: 2-D array of vectors
        faiss_db: New FAISS index stored in "FORAGER/vector_database/index_db.faiss"
    """
    global faiss_db
    global chunks

    print(f"Filepath being used: {filepath}\n")
    # Initially opens the JSONL file, making each line a dictionary

    with open(filepath, "r", encoding="utf-8") as f:
        chunks = [json.loads(line) for line in f if line.strip()]

    # Embed all chunks initially in the JSONL and put them into the FAISS database
    embeddings = embed_chunks(chunks, 0, len(chunks))

    faiss_db.add(embeddings)
    print(f"\033[1;92m✅ {faiss_db.ntotal} chunks successfully inserted into new FAISS database!\033[0m\n")

    # Write to the .faiss file to save the database
    faiss.write_index(faiss_db, "FORAGER/vector_database/index_db.faiss")
    print(f"\033[1;92m✅ FAISS database stored in {faiss_db_filepath}!\033[0m\n")
    return embeddings, faiss_db

def add_to_FAISS(new_embedded_chunks):
    """
    Function to embed and add chunks from newly uploaded documents into FAISS

    Arguments:
        new_embedded_chunks: New vectors to add to FAISS database
    """

    faiss_db.add(new_embedded_chunks)
    faiss.write_index(faiss_db, faiss_db_filepath)

def search_database(query, num_vectors):
    """
    Function to search the FAISS database for the closest k chunks to the query (based on dot product)
    
    Arguments:
        query: User query or LLM response
        num_vectors: Number of closest vectors to return
    """

    global prefix
    global chunks
    global embeddings

    # Embed query
    query_with_prefix = [prefix + query]
    query_emb = model.encode(query_with_prefix, normalize_embeddings = True).astype("float32")

    # Ensure k <= length of index
    num_vectors = min(num_vectors, faiss_db.ntotal)

    # Search index
    scores, indices = faiss_db.search(query_emb, num_vectors)
    # print(f"Scores: \n{scores}\n")
    # print(f"indices: \n{indices}\n")

    # Show results
    print(f"\n\033[1;94mReturning the {num_vectors} most similar chunks for query: \"{query}\"\033[0m\n")
    # print(chunks)
    for rank, idx in enumerate(indices[0]):
        print(f"{rank+1}. Source: {chunks[idx]['source_filename']} \nChunk: {chunks[idx]['chunk_id']} \nScore: {scores[0][rank]:.4f}\n")
        print(f"{chunks[idx]['text']}\n")

def print_vector_in_array(embeddings, n):
    """
    Prints a vector in the 2-D array of chunk vectors at entry n

    Arguments:
        embeddings: 2-D array of chunk vectors
        n: row of array to print (which vector)
    """
    print(f"Printing embedded vector at entry {n}...")
    print(f"{embeddings[n]}\n")

def print_vector_in_FAISS(n):
    """
    Prints a specified vector in the FAISS database

    Arguments: 
        n: id of vector to print
    """
    print(f"Printing vector in FAISS index at entry {n}...")
    print(f"{faiss_db.reconstruct(n)}\n")

def clear_database():
    """
    Takes everything out of the FAISS database, if necessary.
    """
    faiss_db.reset()

#----------------------------#
# Execution                  #
#----------------------------#

# Read in the FAISS database if it exists, or embed chunks and make a new one if it doesn't
if os.path.exists(faiss_db_filepath):
    faiss_db = faiss.read_index(faiss_db_filepath)
    print(f"\033[1.96mFAISS database size: {faiss_db.ntotal}\033[0m\n")
else:
    embed_array, faiss_db = initial_embed_and_build(chunk_filepath)
    print(f"\033[1.96mFAISS database size: {faiss_db.ntotal}\033[0m\n")

# Read in chunks.jsonl
with open(chunk_filepath, "r", encoding="utf-8") as f:
    chunks = [json.loads(line) for line in f if line.strip()]

# Check if more has been added to chunks.jsonl
if len(chunks) > faiss_db.ntotal:
    new_chunks = embed_chunks(chunks, faiss_db.ntotal, len(chunks))
    add_to_FAISS(new_chunks)
    print(f"\033[1.96mFAISS database size: {faiss_db.ntotal}\033[0m\n")
else:
    print(f"\033[1;92m✅ Database is up to date.\033[0m\n")


# Test search
test_query = "What is heterogeneous integration?"
print(test_query)
search_database(test_query, 5)




