"""
What this file does:
Using the jsonl file with each line being a separate json representing a chunk...
1. Embeds each chunk
2. Stores each embedded chunk in FAISS database
3. Includes search function

Still need to do:
1. Figure out how to add to existing FAISS database and not make a new one each time documents are uploaded
    (add_to_index function?)
"""

import os 
from sentence_transformers import SentenceTransformer
import numpy as np
import faiss
import json

# Initialize global variables
dim = 768 # Length of vectors generated by this embedding model
faiss_index = faiss.IndexFlatIP(dim)
data = []
embeddings = []
prefix = "Represent this sentence for retrieval: "
prev_chunk_file_length = 0

# Start by preparing the embedding model
model = SentenceTransformer("BAAI/bge-base-en-v1.5")

# Path to JSONL file with chunks
chunk_filepath = "FORAGER_corpus/heterogenous_integration/chunks/chunks.jsonl"

def embed_chunks(filepath, m, n):
    """
    Takes one chunk at a time from the chunks.jsonl file (or other inputted file) and embeds it using BGE model

    Arguments: 
        filepath: The file path of the JSONL document containing the chunks genereated by ingestor.py and chunker.py
        m: Starting chunk entry
        n: Ending chunk entry
    Returns:
        A 2-D numpy array of vectors for each embedded chunk

    Variable type info: 
        chunk - dictionary (and each line in the JSONL file is a chunk)
        list of chunks - Python list
        text in chunk - one value in the chunk dictionary associated with "text" key
        "embeddings" - 2-D array (specifically "np.ndarray") with all the vectors. Each vector has a length of 768 using the BGE model
        Each element of "embeddings" is also of the type np.ndarray
        The dimensions of the "embeddings" array are [(length of chunk file), 768]
    """

    global data
    global prefix
    global embeddings
    global prev_chunk_file_length

    # Opens the JSONL file, making each line into a dictionary
    with open(filepath, "r", encoding="utf-8") as f:
        data = [json.loads(line) for line in f if line.strip()]

    #new_chunk_file_length = len(data)

    # Select chunks to embed
    chunks_to_embed = data[m:n]

    print(f"\033[1;94mEmbedding {len(chunks_to_embed)} chunks...\033[0m\n")

    # Extract and prefix the text
    texts = [prefix + d["text"] for d in chunks_to_embed] #The BGE model expects the prefix to come before what we want to embed

    len_before_embed = len(embeddings)
    # Embed each chunk and normalize the resulting vector. Convert to float32 for insertion into FAISS index
    embeddings = model.encode(texts, normalize_embeddings = True).astype("float32")

    print(f"\033[1;92m✅ {len(embeddings) - len_before_embed} chunks successfully embedded!\033[0m\n")
    # Return the 2-D array of vectors
    return embeddings

def initial_embed_and_build(filepath): # done
    """
    Run this once when first running FORAGER to embed the first set of chunks and create the FAISS database
    Takes the path to the file with all of the 

    Returns: new FAISS index
    """
    global faiss_index
    global prev_chunk_file_length
    global data

    # Initially opens the JSONL file, making each line into a dictionary
    with open(chunk_filepath, "r", encoding="utf-8") as f:
        data = [json.loads(line) for line in f if line.strip()]

    # Store length so we know if there are new chunks later
    prev_chunk_file_length = len(data)

    # Embed all chunks initially in the JSONL and put them into the FAISS index
    embeddings = embed_chunks(filepath, 0, 10) #should be prev_chunk_file_length - just doing 10 chunks for testing
    faiss_index.add(embeddings)
    print(f"\033[1;92m✅ {faiss_index.ntotal} chunks successfully inserted into new FAISS index!\033[0m\n")
    return embeddings, faiss_index

def add_vectors_to_FAISS(filepath, m, n):
    """
    Function to embed and add chunks from newly uploaded documents into FAISS

    Maybe track length of chunks.jsonl and iteratively add new chunks if the length is longer
    Ex. chunks.jsonl is 801 lines now. Store this current length. Later, say the length is 900. 
    Store this as a temporary variable, add lines 802-900, then replace the 801 with 900 for the current length
    """

    global chunk_file_length


def search_index(faiss_index, query, k):
    """
    Function to search the FAISS database for the closest k chunks to the query (based on dot product)
    
    Arguments:
        query: What the user types into Groq
        k: Number of closest vectors to return
    """

    global prefix

    # Embed query
    query_with_prefix = [prefix + query]
    query_emb = model.encode(query_with_prefix, normalize_embeddings = True).astype("float32")

    # Ensure k <= length of index
    print(f"faiss_index.ntotal = {faiss_index.ntotal}\n")
    k = min(k, faiss_index.ntotal)

    # Search index
    scores, indices = faiss_index.search(query_emb, k)

    # Show results
    print(f"\n\033[1;94mReturning the {k} most similar chunks for query: \"{query}\"\033[0m\n")
    for rank, idx in enumerate(indices[0]):
        print(f"Current idx value: {idx}\n")
        print(f"{rank+1}. Source: {data[idx]["source_filename"]} \nChunk: {data[idx]["chunk_id"]} \nScore: {scores[0][rank]:.4f}\n")
        print(f"{data[idx]["text"]}\n")
    
def store_new_chunks():
    """
    Pass in previous length of chunk file
    Load chunk file
    embed and store chunks from that length index to the end of the file
    if file is same length, say there were no new chunks to add
    """

def print_vector_in_array(embeddings, n): # done
    """
    Prints a vector in the 2-D array of chunk vectors at entry n

    Arguments:
        embeddings: 2-D array of chunk vectors
        n: row of array to print (which vector)
    """
    print(f"Printing embedded vector at entry {n}...")
    print(f"{embeddings[n]}\n")

def print_vector_in_FAISS(faiss_index, n): # done
    """
    Prints a specified vector in the FAISS database

    Arguments: 
        faiss_index: The FAISS index in use
        n: id of vector to print
    """
    print(f"Printing vector in FAISS index at entry {n}...")
    print(f"{faiss_index.reconstruct(n)}\n")

# Running
# if os.path.exists("index.faiss"):
#     index = faiss.read_index("index.faiss")          # ~100 ms
#     metadata = load_jsonl("metadata.jsonl")          # fast streaming
else:
    embed_array, faiss_db = initial_embed_and_build(chunk_filepath)        # heavy only first time

# Testing
# print("Starting initial embed and build\n")
# embed_array, faiss_db = initial_embed_and_build(chunk_filepath)
# print("Finished\n")
# print_vector_in_array(embed_array, 1)
# print_vector_in_FAISS(faiss_db, 2)
test_query = "What is required for an Si base?"
print(test_query)
search_index(faiss_db, test_query, 3)

"""
if os.path.exists("index.faiss"):
    index = faiss.read_index("index.faiss")          # ~100 ms
    metadata = load_jsonl("metadata.jsonl")          # fast streaming
else:
    index, metadata = build_everything_once()        # heavy only first time

# Later, to append:
new_vecs = model.encode(new_chunks, normalize_embeddings=True).astype("float32")
index.add(new_vecs)
append_to_jsonl("metadata.jsonl", new_meta)
faiss.write_index(index, "index.faiss")              # quick overwrite

"""


