"""
This module handles embedding of textual chunks and managing a FAISS vector database for efficient similarity search. 
It is a core component of the FORAGER pipeline, enabling retrieval-augmented generation (RAG) by linking user queries 
to relevant chunks of information from a preprocessed corpus.

Core Functionality:
1. Embeds each chunk from a JSONL file (where each line is a JSON object containing a chunk of text) using the BGE embedding model.
2. Stores these embedded vectors in a FAISS database to enable fast nearest-neighbor search.
3. Provides a search function to retrieve the most relevant chunks for any given query.

Key Features:
- Supports initial creation of the FAISS database or loading from an existing index.
- Automatically updates the FAISS index if new chunks are appended to the source JSONL file.
- Includes utility functions for debugging and inspecting vectors.

Potential Extensions:
- Can be modified to embed chunks from alternate sources beyond the default 'chunks.jsonl'.
- Flexible enough to support future improvements in embedding models or chunking strategies.
"""
import os 
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
__docformat__ = "google"

from sentence_transformers import SentenceTransformer
import numpy as np
import faiss
import json
import time


# Initialize global variables
dim = 768 # Length of vectors generated by this embedding model
faiss_db = faiss.IndexFlatIP(dim)
# chunks = []
embeddings = []
prefix = "Represent this sentence for retrieval: "

# Start by preparing the embedding model
model = SentenceTransformer("BAAI/bge-base-en-v1.5")
# print("Current working directory:", os.getcwd())
# Important filepaths listed here
base_dir = os.path.dirname(os.path.abspath(__file__))
chunk_filepath = os.path.join(base_dir, "..", "FORAGER_corpus", "heterogenous_integration", "chunks", "chunks.jsonl")
faiss_db_filepath = os.path.join(base_dir, "..", "vector_database", "index_db.faiss")


def load_chunks():
    # global chunks
    with open(chunk_filepath, "r", encoding="utf-8") as f:
        chunks = [json.loads(line) for line in f if line.strip()]
    return chunks
    
def embed_chunks(data, m, n): # Working on speeding this up
    """
    Takes one chunk at a time from the new additions to chunks.jsonl file (or other inputted file) and embeds it using BGE model

    Args: 
        filepath: The file path of the JSONL document containing the chunks genereated by ingestor.py and chunker.py
        m: Starting chunk entry
        n: Ending chunk entry
    Returns:
        embeddings: A 2-D numpy array of vectors, each representing a chunk

    Variable type info: 
        chunk - dictionary (and each line in the JSONL file is a chunk)
        list of chunks - Python list
        text in chunk - one value in the chunk dictionary associated with "text" key
        "embeddings" - 2-D array (specifically "np.ndarray") with all the vectors. Each vector has a length of 768 using the BGE model
        Each element of "embeddings" is also of the type np.ndarray
        The dimensions of the "embeddings" array are [(length of chunk file), 768]
    """

    global prefix
    global embeddings

    # Select chunks to embed
    chunks_to_embed = data[m:n]
    print(f"\033[1;94mEmbedding {len(chunks_to_embed)} chunks...\033[0m\n")

    # Extract and prefix the text
    texts = [prefix + d["text"] for d in chunks_to_embed] #The BGE model expects the prefix to come before what we want to embed
    len_before_embed = len(embeddings)

    # Embed each chunk and normalize the resulting vector. Convert to float32 for insertion into FAISS index
    embeddings = model.encode(texts, normalize_embeddings = True, batch_size = 128, show_progress_bar = True).astype("float32")
    print(f"\033[1;92m✅ {len(embeddings) - len_before_embed} chunks successfully embedded!\033[0m\n")

    # Return the 2-D array of vectors
    return embeddings

def initial_embed_and_build(filepath=chunk_filepath):
    """
    Run this once when first running FORAGER to embed the first set of chunks and create the FAISS database

    Args:
        filepath (str): path to the JSONL file containing the chunks to be embedded

    Returns:
        embeddings: 2-D array of vectors
        faiss_db: New FAISS index stored in "FORAGER/vector_database/index_db.faiss"
    """
    global faiss_db
    # global chunks

    chunks = load_chunks()

    # Embed all chunks initially in the JSONL and put them into the FAISS database
    embeddings = embed_chunks(chunks, 0, len(chunks))

    faiss_db.add(embeddings)
    print(f"\033[1;92m✅ {faiss_db.ntotal} chunks successfully inserted into new FAISS database!\033[0m\n")

    # Write to the .faiss file to save the database
    faiss.write_index(faiss_db, faiss_db_filepath)
    print(f"\033[1;92m✅ FAISS database stored in {faiss_db_filepath}!\033[0m\n")
    return embeddings, faiss_db

def add_to_FAISS(new_embedded_chunks):
    """
    Function to embed and add chunks from newly uploaded documents into FAISS

    Args:
        new_embedded_chunks: New vectors to add to FAISS database
    """

    faiss_db.add(new_embedded_chunks)
    faiss.write_index(faiss_db, faiss_db_filepath)

def search_database(query, num_vectors):
    """
    Function to search the FAISS database for the closest k chunks to the query (based on dot product)
    
    Args:
        query: User query or LLM response
        num_vectors: Number of closest vectors to return

    Returns:
        supporting_docs (list): A list of dictionaries. Each dictionary gives the rank, source, order, score, and text of each retrieved chunk.
    """

    global prefix
    # global chunks
    global embeddings

    chunks = load_chunks()
    supporting_docs = []

    # Embed query
    query_with_prefix = [prefix + query]
    query_emb = model.encode(query_with_prefix, normalize_embeddings = True).astype("float32")

    # Ensure k <= length of index
    num_vectors = min(num_vectors, faiss_db.ntotal)

    # Search index
    scores, indices = faiss_db.search(query_emb, num_vectors)
    # print(f"Scores: \n{scores}\n")
    # print(f"indices: \n{indices}\n")

    # Show results
    print(f"\n\033[1;94mReturning the {num_vectors} most similar chunks for query: \"{query}\"\033[0m\n")
    # print(chunks)
    for rank, idx in enumerate(indices[0]):
        # print(f"{rank+1}. Source: {chunks[idx]['source_filename']} \nChunk: {chunks[idx]['chunk_id']} \nScore: {scores[0][rank]:.4f}\n")
        # print(f"{chunks[idx]['text']}\n")
        
        chunk = chunks[idx]
        chunk_result = {
            "rank": rank + 1,
            "source_filename": chunk["source_filename"],
            "chunk_id": chunk["chunk_id"],
            "score": float(scores[0][rank]),
            "text": chunk["text"]
        }
        supporting_docs.append(chunk_result)

    return supporting_docs

def print_vector_in_array(embeddings, n):
    """
    Prints a vector in the 2-D array of chunk vectors at entry n.

    Args:
        embeddings: 2-D array of chunk vectors
        n: row of array to print (which vector)
    """
    print(f"Printing embedded vector at entry {n}...")
    print(f"{embeddings[n]}\n")

def print_vector_in_FAISS(n):
    """
    Prints a specified vector in the FAISS database

    Args: 
        n: id of vector to print
    """
    print(f"Printing vector in FAISS index at entry {n}...")
    print(f"{faiss_db.reconstruct(n)}\n")

def clear_database():
    """
    Takes everything out of the FAISS database, if necessary.
    """
    faiss_db.reset()

def initialize_faiss():
    
    global faiss_db #, chunks
    global chunk_filepath, faiss_db_filepath
    os.makedirs(os.path.dirname(chunk_filepath), exist_ok=True)
    os.makedirs(os.path.dirname(faiss_db_filepath), exist_ok=True)
    
    # Read in the FAISS database if it exists, or embed chunks and make a new one if it doesn't
    if os.path.exists(faiss_db_filepath):
        start_time = time.time()
        faiss_db = faiss.read_index(faiss_db_filepath)
        print(f"\033[1;96mFAISS database size: {faiss_db.ntotal}\033[0m\n")
        end_time = time.time()
        print(f"Loading FAISS index took {end_time - start_time:.2f} seconds")
    else:
        start_time = time.time()
        embed_array, faiss_db = initial_embed_and_build()
        end_time = time.time()
        print(f"Initial embed and build took {end_time - start_time:.2f} seconds")
        print(f"\033[1;96mFAISS database size: {faiss_db.ntotal}\033[0m\n")

    # Check if more has been added to chunks.jsonl
    chunks = load_chunks()
    if len(chunks) > faiss_db.ntotal:
        new_chunks = embed_chunks(chunks, faiss_db.ntotal, len(chunks))
        add_to_FAISS(new_chunks)
        print(f"\033[1;96mFAISS database size: {faiss_db.ntotal}\033[0m\n")
    else:
        print(f"\033[1;92m✅ Database is up to date.\033[0m\n")

#----------------------------#
# Execution                  #
#----------------------------#

# if __name__ == "__main__":
#     print("Hello")
#     load_chunks()
#     initialize_faiss()





