import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from FORAGER.llm_extractor import extract_atomic_claims_llm
from FORAGER.bs import detect_bs
from FORAGER.embedder import FAISSEmbedder
from FORAGER.runner import get_llm_response
from FORAGER.confidence import check_confidence
from FORAGER.pll_controller import prompt_locked_loop
print("✅ test_pipeline.py successfully imported")

# Uncomment if running directly
# initialize_faiss()

def full_forager_pipeline(question: str, k: int = 3):
    """
    Runs the full FORAGER pipeline to answer a user question with traceable, grounded context.

    Pipeline Steps:
    1. Retrieve the top-k most semantically similar document chunks to the input question using FAISS.
    2. Generate an initial LLM answer using the retrieved context (RAG).
    3. Extract atomic claims from the LLM's answer using a claim extraction model.
    4. Evaluate each claim using:
        - a BS detector (Natural Language Inference) to classify claims as Supported, Unsupported, or Contradicted.
        - a confidence checker to determine High, Medium, Low, or Zero confidence based on semantic similarity.
    5. Format claims and their evaluations in a structured output for downstream PLL refinement.

    Args:
        question (str): The user query to be answered using the knowledge base.
        k (int): Number of top chunks to retrieve from the FAISS index. Default is 3.

    Returns:
        answer (str): The initial answer generated by the LLM based on the retrieved context.
        eval (dict): A dictionary where:
            - Keys are atomic claim strings extracted from the answer.
            - Values are dictionaries with:
                - "label" (str): BS detector classification ("Supported", "Unsupported", or "Contradicted").
                - "confidence" (str): Confidence score ("High Confidence", "Medium Confidence", "Low Confidence", or "Zero Confidence").
                - "supporting_chunks" (list): List of supporting document chunks (dicts with metadata like rank, source filename, score, and text) used for evaluating the claim.

    Example return format:
        answer = "3D HI reduces wiring length by using embedded bridge chips."
        eval = {
            "3D HI reduces wiring length": {
                "label": "Supported",
                "confidence": "High Confidence",
                "supporting_chunks": [chunk1_dict, chunk2_dict, chunk3_dict]
            },
            ...
        }
    """
    print("✅ Starting full_forager_pipeline()...")
    base_dir = os.path.dirname(os.path.abspath(__file__))
    chunk_filepath = os.path.join(base_dir, "..", "FORAGER_corpus", "heterogenous_integration", "chunks", "chunks.jsonl")
    faiss_db_filepath = os.path.join(base_dir, "vector_database", "index_db.faiss")
    embedder = FAISSEmbedder(chunk_path = chunk_filepath, faiss_db_path = faiss_db_filepath)
    embedder.initialize_faiss()
    print("✅ FAISS initialized in pipeline scope.")

    # Step 1: Retrieve documents
    try:
        retrieved_docs = embedder.search_database(question, k)
        print(f"✅ Retrieved {len(retrieved_docs)} docs")
    except Exception as e:
        print(f"❌ Error during search_database(): {type(e).__name__}: {e}")
        raise e
    
    retrieved_docs_text = [doc["text"] for doc in retrieved_docs]
    print(f"Chunks used for answer: {retrieved_docs_text}")
    retrieved_docs_combined = "\n\n".join([doc["text"] for doc in retrieved_docs])
    
    # Step 2: Feed question and documents to LLM
    prompt = f"""
    You are answering the following question using ONLY the provided context. DO NOT use any outside knowledge at all.

    Question: {question}

    Context:
    {retrieved_docs_combined}

    Answer:
    """

    # Step 3: Get the LLM's answer
    # print(f"Prompt to LLM:\n{prompt}")
    answer = get_llm_response(prompt)
    # print(f"✅ LLM Answer:\n{answer}")

    # Step 4: Extract claims from LLM answer
    claims = extract_atomic_claims_llm(answer) # a list of all the atomic claims made by the LLM

    # Step 5: Run all claims through BS detector
    eval = {} # dict to map claim to eval_label
    for claim in claims:
        label = detect_bs(claim, supporting_docs=retrieved_docs_text)
        eval[claim] = label

    # Run confidence checker
    updated_eval = {}
    for claim, label in eval.items():
        confidence = check_confidence(claim, label, retrieved_docs)
        updated_eval[claim] = {"label": label, "confidence": confidence, "supporting_chunks": retrieved_docs}
    
    eval = updated_eval
    print(eval)

    return answer, eval


# dummy_eval = [
#     {"claim": "3D HI reduces wiring length.", "label": "Unsupported", "confidence": "Medium"},
#     {"claim": "3D HI increases flexibility.", "label": "Supported", "confidence": "Low"},
# ]
# from ingestor import extract_all_pdfs
# from chunker import main
# dummy_docs = ["3D HI allows better interconnect density.", "It may lead to better performance due to shorter connections."]
# extract_all_pdfs()
# main()
# initialize_faiss()

# prompt_locked_loop("What are some benefits of 3D HI?", dummy_eval, dummy_docs)